## Book Solutions
### Chapter 13: Modeling with Linear Regression
---

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:
data = np.array([[3,6],[3.5,9],[4,8]])
data

array([[3. , 6. ],
       [3.5, 9. ],
       [4. , 8. ]])

In [8]:
reg = LinearRegression().fit(data[:,0].reshape(-1, 1), data[:,1].reshape(-1, 1))

In [9]:
reg.intercept_

array([0.66666667])

In [10]:
reg.coef_

array([[2.]])