## Book Solutions
### Chapter 14: Classification with Logistic Regression
---

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [3]:
data = np.array([[3,0],[3.2,0],[4,1]])
data

array([[3. , 0. ],
       [3.2, 0. ],
       [4. , 1. ]])

In [5]:
reg = LogisticRegression().fit(data[:,0].reshape(-1, 1), data[:,1])

In [6]:
reg.intercept_

array([-2.5127071])

In [7]:
reg.coef_

array([[0.53268991]])

In [13]:
reg.predict(np.array([6]).reshape(-1,1))

array([1.])